name: Pantry

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.3
      uses: actions/setup-python@v1
      with:
        python-version: '3.8.3'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Linting
      run: scripts/linting.sh
